# Generated by Django 6.0.3 on 2026-03-16 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='NULL indica que el registro está activo.', null=True, verbose_name='Eliminado el')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de transacción')),
                ('receiver_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='wallet.account', verbose_name='Cuenta receptora')),
                ('sender_account', models.ForeignKey(blank=True, help_text='NULL indica que es un depósito externo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_transactions', to='wallet.account', verbose_name='Cuenta remitente')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
