# Generated by Django 6.0.3 on 2026-03-18 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='message',
            field=models.CharField(blank=True, default='', help_text='Mensaje opcional del remitente.', max_length=255, verbose_name='Mensaje'),
        ),
    ]
